import { supabaseAdmin } from "@/lib/supabase-admin";
import { RaceInput } from "@/lib/race-engineer-analysis";

type P={event?:string;session?:number|string;sessionType?:number;startTime?:string;tow?:boolean;towed?:boolean};
type Lap={car_id:number;track_id:number;lap_number:number|null;lap_time:number|null;incomplete:boolean|null;missing:boolean|null;discontinuity:boolean|null;pit_in:boolean|null;pit_out:boolean|null;garage61_payload:unknown};
type Event={racedAt:string;context:string;delta:number;positionChange:number|null;type:string;confidence:"driver"|"confirmed"|"probable";completedLaps:number;timeOnTrackSeconds:number;progressPct:number|null};
const key=(s:string)=>s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]/g,"");
const same=(a:string|undefined,b:string)=>!!a&&(a===b||a.includes(b)||b.includes(a)||(a.length>=8&&b.length>=8&&a.slice(0,8)===b.slice(0,8)));
async function allLaps(driverId:string){const out:Lap[]=[];for(let from=0;;from+=1000){const{data,error}=await supabaseAdmin.from("laps").select("car_id,track_id,lap_number,lap_time,incomplete,missing,discontinuity,pit_in,pit_out,garage61_payload").eq("driver_id",driverId).range(from,from+999);if(error)throw error;out.push(...((data??[])as Lap[]));if(!data||data.length<1000)return out}}

export async function retirementEvents(driverId:string,races:RaceInput[],seasonName:string){
 const[{data:cars,error:ce},{data:tracks,error:te},laps]=await Promise.all([supabaseAdmin.from("cars").select("id,name"),supabaseAdmin.from("tracks").select("id,name"),allLaps(driverId)]);if(ce)throw ce;if(te)throw te;
 const car=new Map((cars??[]).map(x=>[x.id,key(x.name)])),track=new Map((tracks??[]).map(x=>[x.id,key(x.name)])),groups=new Map<string,Lap[]>();
 for(const lap of laps){const p=(lap.garage61_payload??{})as P;if(!p.startTime||!(p.sessionType===2||p.sessionType===3))continue;const groupKey=String(lap.car_id)+":"+String(lap.track_id)+":"+(p.event??"")+":"+(p.session??"");groups.set(groupKey,[...(groups.get(groupKey)??[]),lap])}
 const detected:Array<Omit<Event,"progressPct"> & {contextKey:string}>=[],durations=new Map<string,number[]>(),sessionsByRace=new Map<string,{seconds:number;laps:number;contextKey:string}[]>();
 for(const rows of groups.values()){const p=(rows[0].garage61_payload??{})as P;if(!p.startTime)continue;const start=new Date(p.startTime).getTime(),cn=car.get(rows[0].car_id),tn=track.get(rows[0].track_id),race=races.filter(r=>same(cn,key(r.car_name))&&same(tn,key(r.track_name))).sort((a,b)=>Math.abs(new Date(a.raced_at).getTime()-start)-Math.abs(new Date(b.raced_at).getTime()-start))[0];if(!race||Math.abs(new Date(race.raced_at).getTime()-start)>2*3600000)continue;
  const contextKey=key(race.car_name)+"|"+key(race.track_name),seconds=rows.reduce((total,lap)=>total+(typeof lap.lap_time==="number"&&lap.lap_time>0?lap.lap_time:0),0),completedLaps=rows.filter(lap=>typeof lap.lap_time==="number"&&lap.lap_time>0).length,raceKey=race.raced_at+"|"+race.car_name+"|"+race.track_name;
  durations.set(contextKey,[...(durations.get(contextKey)??[]),seconds]);sessionsByRace.set(raceKey,[...(sessionsByRace.get(raceKey)??[]),{seconds,laps:completedLaps,contextKey}]);
  const confirmed=rows.some(l=>{const q=(l.garage61_payload??{})as P;return q.tow===true||q.towed===true}),interrupted=rows.some(l=>(l.incomplete===true||l.missing===true||l.discontinuity===true)&&(l.pit_in===true||l.pit_out===true)),last=[...rows].sort((a,b)=>(b.lap_number??0)-(a.lap_number??0))[0],terminal=rows.length>=3&&!!last&&(last.incomplete===true||last.missing===true||last.discontinuity===true),damagingFinish=(race.irating_after-race.irating_before)<0&&(race.position_change??0)<=-3;if(!confirmed&&!interrupted&&!(terminal&&damagingFinish))continue;
  detected.push({racedAt:race.raced_at,context:race.car_name+" • "+race.track_name,contextKey,delta:race.irating_after-race.irating_before,positionChange:race.position_change,type:confirmed?"Tow confirmado":interrupted?"Retirada provável (pit + volta interrompida)":"Retirada provável (volta final interrompida + resultado danoso)",confidence:confirmed?"confirmed":"probable",completedLaps,timeOnTrackSeconds:seconds});
 }
 const driverRace=races.find(r=>Math.abs(new Date(r.raced_at).getTime()-new Date("2026-09-04T18:30:00.000Z").getTime())<=30*60000&&key(r.car_name).includes("sf23")&&key(r.track_name).includes("silverstone"));
 if(driverRace){const raceKey=driverRace.raced_at+"|"+driverRace.car_name+"|"+driverRace.track_name,session=[...(sessionsByRace.get(raceKey)??[])].sort((a,b)=>b.seconds-a.seconds)[0],contextKey=key(driverRace.car_name)+"|"+key(driverRace.track_name);detected.push({racedAt:driverRace.raced_at,context:driverRace.car_name+" • "+driverRace.track_name,contextKey,delta:driverRace.irating_after-driverRace.irating_before,positionChange:driverRace.position_change,type:"Tow / abandono confirmado pelo piloto",confidence:"driver",completedLaps:session?.laps??driverRace.laps??0,timeOnTrackSeconds:session?.seconds??0})}
 const unique=new Map<string,typeof detected[number]>();for(const event of detected){const eventKey=event.racedAt+"|"+event.context,old=unique.get(eventKey),priority=(x:typeof event)=>x.confidence==="driver"?4:x.confidence==="confirmed"?3:x.type.includes("pit +")?2:1;if(!old||priority(event)>priority(old))unique.set(eventKey,event)}
 return[...unique.values()].map(event=>{const reference=Math.max(...(durations.get(event.contextKey)??[]),0);const{contextKey,...rest}=event;return{...rest,progressPct:reference>0?Number(Math.min(100,event.timeOnTrackSeconds/reference*100).toFixed(1)):null}}).sort((a,b)=>a.confidence!==b.confidence?(a.confidence==="driver"?-1:b.confidence==="driver"?1:a.confidence==="confirmed"?-1:1):a.delta-b.delta);
}
