import { gzipSync } from "node:zlib";
import { supabaseAdmin } from "@/lib/supabase-admin";
const BUCKET="telemetry",MAX_FILE_BYTES=8*1024*1024,BUDGET=900*1024*1024,BATCH=24,COMPACTION_BATCH=10;
type Entry={id?:string|null;name:string;metadata?:{size?:number}|null};
type Payload={season?:{name?:string};sessionType?:number;session_type?:number;session?:string};
type Candidate={id:string;track_id:number|null;garage61_payload?:Payload};
const pathOf=(prefix:string,name:string)=>prefix?prefix+"/"+name:name;
async function list(prefix="",out:string[]=[]):Promise<string[]>{const q=await supabaseAdmin.storage.from(BUCKET).list(prefix,{limit:1000});if(q.error)throw q.error;for(const e of(q.data??[])as Entry[]){const p=pathOf(prefix,e.name);if(e.id&&p.endsWith(".csv"))out.push(p);else if(!e.id)await list(p,out);if(out.length>=COMPACTION_BATCH)break}return out}
async function used(prefix=""):Promise<number>{const q=await supabaseAdmin.storage.from(BUCKET).list(prefix,{limit:1000});if(q.error)throw q.error;let total=0;for(const e of(q.data??[])as Entry[]){total+=e.id?Number(e.metadata?.size??0):await used(pathOf(prefix,e.name))}return total}
async function compact(){let files=0,saved=0;for(const source of await list()){const d=await supabaseAdmin.storage.from(BUCKET).download(source);if(d.error||!d.data)continue;const raw=Buffer.from(await d.data.arrayBuffer()),gz=gzipSync(raw,{level:9}),target=source+".gz";if(gz.length>=raw.length)continue;const up=await supabaseAdmin.storage.from(BUCKET).upload(target,gz,{contentType:"application/gzip"});if(up.error)continue;const db=await supabaseAdmin.from("laps").update({telemetry_path:target}).eq("telemetry_path",source);if(db.error){await supabaseAdmin.storage.from(BUCKET).remove([target]);continue}const rm=await supabaseAdmin.storage.from(BUCKET).remove([source]);if(!rm.error){files++;saved+=raw.length-gz.length}}return{files,saved}}
const isRace=(p:Payload)=>{const t=p.sessionType??p.session_type;return p.session==="Race"||t===2||t===3};
export async function runTelemetryBackfill(){const compaction=await compact();let bytes=await used();const season=await supabaseAdmin.from("v_season_summary").select("season_name,season_id").order("season_id",{ascending:false}).limit(2);if(season.error)throw season.error;const current=season.data?.[0]?.season_name,previous=season.data?.[1]?.season_name;if(!current||!previous)return{status:"no_season_window",compaction};const q=await supabaseAdmin.from("laps").select("id,track_id,garage61_payload").eq("can_view_telemetry",true).is("telemetry_path",null).limit(3000);if(q.error)throw q.error;const ready=(q.data??[] as Candidate[]).filter(l=>{const p=l.garage61_payload??{};return p.season?.name===current||(p.season?.name===previous&&isRace(p))}).slice(0,BATCH);const token=process.env.GARAGE61_API_TOKEN;if(!token)throw new Error("GARAGE61_API_TOKEN não configurado");let downloaded=0;for(const lap of ready){const r=await fetch("https://garage61.net/api/v1/laps/"+encodeURIComponent(lap.id)+"/csv",{headers:{Authorization:"Bearer "+token,Accept:"text/csv"},cache:"no-store"});if(!r.ok)continue;const raw=Buffer.from(await r.arrayBuffer()),gz=gzipSync(raw,{level:9});if(raw.length>MAX_FILE_BYTES||bytes+gz.length>BUDGET)break;const target="laps/"+(lap.track_id??"unknown")+"/"+lap.id+".csv.gz";const up=await supabaseAdmin.storage.from(BUCKET).upload(target,gz,{contentType:"application/gzip"});if(up.error)continue;const db=await supabaseAdmin.from("laps").update({telemetry_path:target,synced_at:new Date().toISOString()}).eq("id",lap.id);if(db.error)throw db.error;bytes+=gz.length;downloaded++}return{status:"ok",retention:{currentSeason:"all sessions",previousSeason:"Race only"},currentSeason:current,previousSeason:previous,downloaded,usedBytes:bytes,budgetBytes:BUDGET,compaction}}