import { gunzipSync } from "node:zlib";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { telemetryFeatures } from "@/lib/telemetry-features";
const BUCKET="telemetry",MAX_FILE_BYTES=8*1024*1024,BATCH=24,LEGACY=12;
type Entry={id?:string|null;name:string};type Candidate={id:string;track_id:number|null;garage61_payload?:{season?:{name?:string}}};
async function files(prefix="",out:string[]=[]):Promise<string[]>{const {data,error}=await supabaseAdmin.storage.from(BUCKET).list(prefix,{limit:1000});if(error)throw error;for(const e of(data??[])as Entry[]){const p=prefix?`${prefix}/${e.name}`:e.name;if(e.id&&(/\.csv(\.gz)?$/).test(p))out.push(p);else if(!e.id)await files(p,out);if(out.length>=LEGACY)break}return out}
async function extract(id:string,raw:Buffer){const {error}=await supabaseAdmin.from("telemetry_features").upsert({lap_id:id,...telemetryFeatures(raw.toString("utf8"))});if(error)throw error}
async function convertLegacy(){let converted=0,released=0;for(const path of await files()){const id=path.match(/([0-9a-f-]{36})\.csv(?:\.gz)?$/i)?.[1];if(!id)continue;const {data}=await supabaseAdmin.storage.from(BUCKET).download(path);if(!data)continue;const bytes=Buffer.from(await data.arrayBuffer()),raw=path.endsWith(".gz")?gunzipSync(bytes):bytes;await extract(id,raw);const {error}=await supabaseAdmin.storage.from(BUCKET).remove([path]);if(!error){converted++;released+=bytes.length}}return{converted,released}}
export async function runTelemetryBackfill(){const compaction=await convertLegacy();const {data:seasons}=await supabaseAdmin.from("v_season_summary").select("season_name,season_id").order("season_id",{ascending:false}).limit(2);const names=(seasons??[]).map(x=>x.season_name);const {data,error}=await supabaseAdmin.from("laps").select("id,track_id,garage61_payload").eq("can_view_telemetry",true).is("telemetry_path",null).limit(1200);if(error)throw error;const ids=(data??[]).map((x:Candidate)=>x.id);const {data:done,error:doneError}=ids.length?await supabaseAdmin.from("telemetry_features").select("lap_id").in("lap_id",ids):{data:[],error:null};if(doneError)throw doneError;const ready=(data??[] as Candidate[]).filter(x=>!(done??[]).some(d=>d.lap_id===x.id)).sort((a,b)=>{const sa=a.garage61_payload?.season?.name,sb=b.garage61_payload?.season?.name;return names.indexOf(sa??"")-names.indexOf(sb??"")}).slice(0,BATCH);const token=process.env.GARAGE61_API_TOKEN;if(!token)throw new Error("GARAGE61_API_TOKEN não configurado");let downloaded=0;for(const lap of ready){const r=await fetch(`https://garage61.net/api/v1/laps/${encodeURIComponent(lap.id)}/csv`,{headers:{Authorization:`Bearer ${token}`,Accept:"text/csv"},cache:"no-store"});if(!r.ok)continue;const raw=Buffer.from(await r.arrayBuffer());if(raw.length>MAX_FILE_BYTES)continue;await extract(lap.id,raw);downloaded++}return{status:"ok",downloaded,compaction,prioritizedSeasons:names}}
