import { gunzipSync } from "node:zlib";
import { supabaseAdmin } from "@/lib/supabase-admin";
import { Category, RaceInput } from "@/lib/race-engineer-analysis";

type Payload={season?:{name?:string};sessionType?:number;session_type?:number;session?:string|number;startTime?:string};
type Lap={id:string;car_id:number;track_id:number;lap_time:number|null;clean:boolean|null;off_track:boolean|null;incomplete:boolean|null;discontinuity:boolean|null;telemetry_path:string|null;garage61_payload?:Payload};
type LapSample={lapTime:number;session:string;gap:number;throttleSmoothness:number|null;brakeSmoothness:number|null;steeringSmoothness:number|null};
const norm=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]/g,"");
const avg=(v:number[])=>v.length?v.reduce((a,b)=>a+b,0)/v.length:null;
const sd=(v:number[])=>{const m=avg(v);return m===null?null:Math.sqrt(avg(v.map(x=>(x-m)**2))??0)};
const round=(v:number|null,d=2)=>v===null?null:Number(v.toFixed(d));
const index=(headers:string[],names:string[])=>headers.findIndex(h=>names.some(n=>h.includes(n)));
function values(lines:string[],column:number){if(column<0)return[];const step=Math.max(1,Math.ceil(lines.length/15000)),out:number[]=[];for(let i=1;i<lines.length;i+=step){const value=Number(lines[i].split(",")[column]);if(Number.isFinite(value))out.push(value)}return out}
const smoothness=(v:number[])=>v.length<2?null:avg(v.slice(1).map((x,i)=>Math.abs(x-v[i])));
const sum=(v:number[])=>v.reduce((a,b)=>a+b,0);
function correlation(a:number[],b:number[]){if(a.length<5||a.length!==b.length)return null;const am=avg(a)!,bm=avg(b)!,num=sum(a.map((x,i)=>(x-am)*(b[i]-bm))),den=Math.sqrt(sum(a.map(x=>(x-am)**2))*sum(b.map(x=>(x-bm)**2)));return den?num/den:null}
const metric=(samples:LapSample[],key:"throttleSmoothness"|"brakeSmoothness"|"steeringSmoothness")=>samples.filter(s=>s[key]!==null).map(s=>({lap:s.gap,input:s[key] as number}));
const repeatability=(pairs:{lap:number;input:number}[])=>{const inputs=pairs.map(x=>x.input),mean=avg(inputs);return mean&&mean!==0?round((sd(inputs)!/Math.abs(mean))*100,1):null};
const correlate=(pairs:{lap:number;input:number}[])=>round(correlation(pairs.map(x=>x.input),pairs.map(x=>x.lap)),2);
const isRace=(payload:Payload)=>payload.session==="Race"||payload.sessionType===2||payload.sessionType===3||payload.session_type===2||payload.session_type===3;
const PAGE=500;

export async function telemetryInputProfile(driverId:string,category:Category,races:RaceInput[],_seasonName:string,week:number|null){
 const names=new Set(races.map(r=>norm(r.car_name)));if(!names.size)return empty("Sem corridas no recorte.");
 const {data:cars,error:ce}=await supabaseAdmin.from("cars").select("id,name");if(ce)throw ce;const ids=(cars??[]).filter(c=>names.has(norm(c.name??""))).map(c=>c.id);if(!ids.length)return empty("Carros do recorte não encontrados.");
 const all:Lap[]=[];for(let from=0;;from+=PAGE){const {data,error}=await supabaseAdmin.from("laps").select("id,car_id,track_id,lap_time,clean,off_track,incomplete,discontinuity,telemetry_path,garage61_payload").eq("driver_id",driverId).in("car_id",ids).not("telemetry_path","is",null).order("id",{ascending:true}).range(from,from+PAGE-1);if(error)throw error;all.push(...((data??[])as Lap[]));if(!data||data.length<PAGE)break}
 const raceTimes=races.map(r=>new Date(r.raced_at).getTime()).filter(Number.isFinite);
 const eligible=all.filter(l=>{const p=l.garage61_payload??{},time=p.startTime?new Date(p.startTime).getTime():NaN;return isRace(p)&&l.clean===true&&l.off_track!==true&&l.incomplete!==true&&l.discontinuity!==true&&typeof l.lap_time==="number"&&l.lap_time>0&&Number.isFinite(time)&&raceTimes.some(race=>Math.abs(time-race)<=2*3600000)}),groups=new Map<string,Lap[]>();for(const lap of eligible){const group=String(lap.car_id)+"|"+String(lap.track_id);groups.set(group,[...(groups.get(group)??[]),lap])}const candidates=[...groups.values()].filter(rows=>rows.length>=2).sort((a,b)=>b.length-a.length).slice(0,4).flatMap(rows=>rows.slice(0,6)).slice(0,24);
 const rawSamples:Array<Omit<LapSample,"gap">>=[];
 for(const lap of candidates){if(!lap.telemetry_path)continue;const d=await supabaseAdmin.storage.from("telemetry").download(lap.telemetry_path);if(d.error||!d.data)continue;let raw=Buffer.from(await d.data.arrayBuffer());try{if(lap.telemetry_path.endsWith(".gz"))raw=gunzipSync(raw)}catch{continue}const lines=raw.toString("utf8").split(/\r?\n/);if(lines.length<3)continue;const headers=lines[0].split(",").map(norm),throttle=values(lines,index(headers,["throttle"])),brake=values(lines,index(headers,["brake"])),steering=values(lines,index(headers,["steeringwheelangle","steering"]));const ts=Math.max(...throttle.map(Math.abs),0)>1.5?100:1,bs=Math.max(...brake.map(Math.abs),0)>1.5?100:1,p=lap.garage61_payload??{};rawSamples.push({lapTime:lap.lap_time!,session:String(lap.car_id)+"|"+String(lap.track_id),throttleSmoothness:smoothness(throttle.map(x=>x/ts)),brakeSmoothness:smoothness(brake.map(x=>x/bs)),steeringSmoothness:smoothness(steering)})}
 const counts=new Map<string,number>();for(const sample of rawSamples)counts.set(sample.session,(counts.get(sample.session)??0)+1);const comparableRaw=rawSamples.filter(sample=>(counts.get(sample.session)??0)>=2);if(!comparableRaw.length)return empty(eligible.length===0?"Nenhum CSV limpo de corrida foi encontrado para as "+String(races.length)+" corridas deste recorte. O backfill precisa carregar a telemetria dessas corridas.":"Foram encontradas "+String(eligible.length)+" voltas limpas de corrida, mas ainda não há duas do mesmo carro e pista para calcular consistência.");
 const bestBySession=new Map<string,number>();for(const sample of comparableRaw)bestBySession.set(sample.session,Math.min(bestBySession.get(sample.session)??Infinity,sample.lapTime));
 const samples:LapSample[]=comparableRaw.map(sample=>({...sample,gap:sample.lapTime-(bestBySession.get(sample.session)??sample.lapTime)})),gaps=samples.map(s=>s.gap),lapStd=sd(gaps),gapMean=avg(gaps),contexts=bestBySession.size,onlyOne=contexts===1,lapTimes=samples.map(s=>s.lapTime),throttle=metric(samples,"throttleSmoothness"),brake=metric(samples,"brakeSmoothness"),steering=metric(samples,"steeringSmoothness");
 return{files:samples.length,laps:samples.length,coverage:String(contexts)+" combinações carro+pista; tempos normalizados pela melhor volta limpa de cada combinação",meanLapSeconds:onlyOne?round(avg(lapTimes),3):null,bestLapSeconds:onlyOne&&lapTimes.length?round(Math.min(...lapTimes),3):null,averageGapToBestSeconds:round(gapMean,3),lapStdDevSeconds:round(lapStd,3),lapCvPct:null,throttleRepeatabilityPct:repeatability(throttle),brakeRepeatabilityPct:repeatability(brake),steeringRepeatabilityPct:repeatability(steering),throttleLapCorrelation:correlate(throttle),brakeLapCorrelation:correlate(brake),steeringLapCorrelation:correlate(steering),note:samples.length>=8?"Cada volta foi comparada apenas com voltas do mesmo carro e pista. A correlação mostra se variar um input acompanhou aumento ou redução do gap.":"Amostra pequena: use os valores como sinal, não como conclusão."};
}
function empty(note:string){return{files:0,laps:0,coverage:"sem cobertura",meanLapSeconds:null,bestLapSeconds:null,averageGapToBestSeconds:null,lapStdDevSeconds:null,lapCvPct:null,throttleRepeatabilityPct:null,brakeRepeatabilityPct:null,steeringRepeatabilityPct:null,throttleLapCorrelation:null,brakeLapCorrelation:null,steeringLapCorrelation:null,note}}
